Add Bicep
Azure-Samples/function-app-arm-templates pull request #1
Opened 2022-08-30 15:16 UTC by mumian

## Purpose
- Update the API versions.
- Add the Bicep file.

## Does this introduce a breaking change?
```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
az deployment group create -f main.bicep -g <Specify-resource-group-name>
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-08-30 15:16 UTC, mumian commented
#sign-off

2022-09-06 20:23 UTC, patelchandni requested changes

2022-09-06 20:23 UTC, patelchandni commented on function-app-windows-consumption/azuredeploy.json
> +      "name": "[format('{0}/{1}', parameters('functionAppName'), 'MSDeploy')]",
We strictly recommend zipdeploy (not MSDeploy) for function ap deployments.

2022-09-06 20:23 UTC, patelchandni commented on function-app-windows-consumption/main.bicep
> +  name: 'MSDeploy'
We strictly recommend zipdeploy (not MSDeploy) for function ap deployments.

2022-09-07 15:13 UTC, patelchandni approved these changes

2022-09-07 15:15 UTC, merged